### ISSUE TITLE
Use _.runInContext

### ISSUE THREAD

**Issue by jdalton** [ascariandrea/turbo-lodash#1]
I noticed in your test files you were mixing in to the lodash package directly. Instead for node land uses you can use [_.runInContext](https://lodash.com/docs#runInContext) to create a pristine lodash instance:

```js
var _ = require('lodash').runInContext();
```

That won't affect the package when extended.

**Comment by ascariandrea** [comment]
Fixed in 5355376808fbfecb4b54d037398f37963d7846c1

**Comment by jdalton** [comment]
Rock!
